<a href="https://colab.research.google.com/github/busraatasoy/veri_bilimi_ve_makine_ogrenmesi_100gun_kamp/blob/main/Day_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas Kütüphanesine Giriş

Python’da veri analizi dendiğinde akla ilk gelen kütüphanelerden biri Pandas’tır. Adını “Panel Data” kavramından alan Pandas, veri manipülasyonu, temizleme ve analiz işlemlerini kolaylaştıran güçlü bir araçtır.

## **🔍 Pandas Nedir?**

Pandas, farklı veri kaynaklarından **(örneğin CSV, Excel, SQL, JSON)** gelen verileri kolayca okuyup tablo formatında işler.
**Yapısal (structured)** veriler üzerinde hızlı, esnek ve sezgisel analiz yapmamızı sağlar.

Kütüphane, iki temel veri yapısına dayanır:

- `Series:` Tek boyutlu (liste benzeri) veri yapısı

- `DataFrame:` Satır ve sütunlardan oluşan tablo yapısı


Linkteki adresten Pandas'ın resmi websitesi ve dökümanlarına erişebilirsiniz: 👉🔗[Pandas website](https://pandas.pydata.org/)

İlave olarak farklı kaynaktan hızlıca pandasın nasıl kullanıldığına erişmek için linki inceleyebilirsiniz:👉🔗[Pandas ek kaynak](https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/)

## ➡ Pandas Nasıl Yüklenir?

Pandas genellikle kısaltması ile birlikte şu şekilde içe aktarılır:



```
import pandas as pd
```
Bu satır sayesinde artık kütüphanedeki fonksiyonlara `pd` kısaltmasıyla erişebiliriz.

## ➡ Pandas Kurulu Değilse Ne Yapmalı?

Google Colab ortamında Pandas önceden kurulu gelir. Ancak kendi bilgisayarınızda çalışırken Pandas yüklü değilse, aşağıdaki komutla yükleyebilirsiniz:



```
!pip install pandas
```
Ardından tekrar `import pandas as pd` yazarak kullanmaya başlayabilirsiniz.

## ➡ Series Yapısı Nedir?

Series, tek boyutlu veri saklamak için kullanılır.
Her elemanın bir indeksi (index) vardır.

In [ ]:
# Pandas kütüphanesini yükleyelim

import pandas as pd

In [ ]:
# Öğrenci notlarının sözlük formunda olduğunu varsayalım:

grades = {"Atil": 50, "James": 60, "Lars": 30}

In [ ]:
# Oluşturduğumuz series yapısına bakalım:

pd.Series(grades)

Atil     50
James    60
Lars     30
dtype: int64

In [ ]:
# İki farklı liste halinde oluşturalım

names = ["Atil", "James", "Lars"]
grades = [50, 60, 30]

In [ ]:
# Names listesini kontrol edelim

pd.Series(names)

0     Atil
1    James
2     Lars
dtype: object

In [ ]:
# grades listesini kontrol edelim

pd.Series(grades)

0    50
1    60
2    30
dtype: int64

In [ ]:
# İki listeye aynı anda bakalım

pd.Series(names, grades)

50     Atil
60    James
30     Lars
dtype: object

In [ ]:
# Argüman ile iki listeye bakalım

pd.Series(data=grades, index=names)

Atil     50
James    60
Lars     30
dtype: int64

In [ ]:
# Numpy dizileri ile kullanalım

# Kütüphaneyi yükleyelim
import numpy as np

# array(dizi) oluşturalım
numpy_array = np.array([50,40,30,20])

In [ ]:
# Numpy dizisinden Pandas Series oluşturalım

pd.Series(numpy_array)

0    50
1    40
2    30
3    20
dtype: int64

## ➡ Series ile Aritmetik İşlemler

In [ ]:
# Aritmetik olarak bakalım

# 1. yarışma sonucu
contest_result = pd.Series(data = [10,5,100], index = ["Atil", "James", "Lars"])

contest_result

Atil      10
James      5
Lars     100
dtype: int64

In [ ]:
# 2. yarışma sonucu

contest_result2 = pd.Series(data = [20,50,10], index = ["Atil", "James", "Lars"])

contest_result2

Atil     20
James    50
Lars     10
dtype: int64

In [ ]:
# Kişi bazlı sonuçlara bakalım

contest_result["Atil"]

np.int64(10)

In [ ]:
contest_result2["James"]

np.int64(50)

In [ ]:
# Final sonucuna bakalım

final_result = contest_result + contest_result2

final_result

Atil      30
James     55
Lars     110
dtype: int64

In [ ]:
# Diğer aritmetik işlemlerde yapılır:

contest_result - contest_result2

Atil    -10
James   -45
Lars     90
dtype: int64

In [ ]:
contest_result * contest_result2

Atil      200
James     250
Lars     1000
dtype: int64

In [ ]:
contest_result / contest_result2

Atil      0.5
James     0.1
Lars     10.0
dtype: float64

In [ ]:
# yeni seri oluşturalım

diff_series = pd.Series([20,30,40,50], ["a", "b", "c", "d"])

diff_series

a    20
b    30
c    40
d    50
dtype: int64

In [ ]:
# farklı index elemanlarıyla yeni seri2 oluşturalım

diff_series2 = pd.Series([10,5,3,1], ["a", "c", "f", "g"])

diff_series2

a    10
c     5
f     3
g     1
dtype: int64

In [ ]:
# Bu serileri toplayalım
# Verileri eşleşmediğinde& bulamadığında NaN değeri verilir.

diff_series + diff_series2

a    30.0
b     NaN
c    45.0
d     NaN
f     NaN
g     NaN
dtype: float64

## ➡  DataFrame Yapısı Nedir?

DataFrame, Pandas’ın en güçlü yapısıdır. Satır ve sütunlardan oluşan tablo benzeri bir veri yapısıdır.

In [ ]:
# Kütüphaneleri yükleyelim

import pandas as pd
import numpy as np

In [ ]:
# Basit veri yapısı oluşturalım(random)

data = np.random.randn(4,3)

data

array([[-0.65216024,  0.17382252,  1.06013638],
       [ 0.26524827,  0.91168222, -0.71226975],
       [-1.26533336, -0.50760648, -0.79841754],
       [-0.72258736,  0.52201165,  0.73579879]])

In [ ]:
# Dataframe oluşturalım

df = pd.DataFrame(data)

df

          0         1         2
0 -0.652160  0.173823  1.060136
1  0.265248  0.911682 -0.712270
2 -1.265333 -0.507606 -0.798418
3 -0.722587  0.522012  0.735799

In [ ]:
# Tip kontrolü yapalım

type(df)

pandas.core.frame.DataFrame

In [ ]:
# Tip kontrolü yapalım
# İlk eleman için

type(df[0])

pandas.core.series.Series

In [ ]:
# Yeni dataframe oluşturalım
# Kolon isimleriyle oluşturalım

new_df = pd.DataFrame(data, index =["Atil", "Zeynep", "Atlas", "Mehmet"], columns=["Salary", "Age", "Seniority"])

new_df

          Salary       Age  Seniority
Atil   -0.652160  0.173823   1.060136
Zeynep  0.265248  0.911682  -0.712270
Atlas  -1.265333 -0.507606  -0.798418
Mehmet -0.722587  0.522012   0.735799

In [ ]:
# Yaş kolonuna erişelim

new_df["Age"]

Atil      0.173823
Zeynep    0.911682
Atlas    -0.507606
Mehmet    0.522012
Name: Age, dtype: float64

In [ ]:
# Maaş kolonuna erişelim

new_df["Salary"]

Atil     -0.652160
Zeynep    0.265248
Atlas    -1.265333
Mehmet   -0.722587
Name: Salary, dtype: float64

In [ ]:
# Birden fazla kolona erişelim

new_df[["Salary", "Seniority"]]

          Salary  Seniority
Atil   -0.652160   1.060136
Zeynep  0.265248  -0.712270
Atlas  -1.265333  -0.798418
Mehmet -0.722587   0.735799

In [ ]:
# Tek bir elemana erişme

#loc → Etiket (isim) bazlı erişim
#loc, etiketleri (index adlarını) kullanarak erişim sağlar.

new_df.loc["Atil"]

Salary      -0.652160
Age          0.173823
Seniority    1.060136
Name: Atil, dtype: float64

In [ ]:
# Tek bir elemana erişme

# iloc → Konum (index numarası) bazlı erişim
# iloc, satır sırasına (index numarasına) göre erişim sağlar.
# Yani iloc[0] ilk satırı döndürür.

new_df.iloc[0]

Salary      -0.652160
Age          0.173823
Seniority    1.060136
Name: Atil, dtype: float64

In [ ]:
# Hücre Bazında Erişim
# loc ile:
# Bazen sadece belirli bir hücreye (örneğin Atil’in yaşı) erişmek isteyebilirsin.
# Bunu şu şekilde yapabiliriz: (satır etiketi, sütun adı)

new_df.loc["Atil", "Age"]

np.float64(0.17382251821871145)

In [ ]:
# Hücre Bazında Erişim
# iloc ile:
# iloc ile (satır index numarası, sütun index numarası)

new_df.iloc[0,1]

np.float64(0.17382251821871145)

In [ ]:
# Hücre Bazında Erişim
# Bütün satırlara erişmek için( Age)
# iloc ile (satır index numarası, sütun index numarası)

new_df.iloc[:,2]

Atil      1.060136
Zeynep   -0.712270
Atlas    -0.798418
Mehmet    0.735799
Name: Seniority, dtype: float64

## ➡  Data Manipülasyonu

In [ ]:
# Veri setine yeni kolon ekleyelim

new_df["Extra"] = 10

new_df

          Salary       Age  Seniority  Extra
Atil   -0.652160  0.173823   1.060136     10
Zeynep  0.265248  0.911682  -0.712270     10
Atlas  -1.265333 -0.507606  -0.798418     10
Mehmet -0.722587  0.522012   0.735799     10

In [ ]:
# Eklediğimiz "Extra" sütununu silelim
# axis = 1 sütunu belirtir.
# inplace = True değişikliği verisetinde kalıcı olarak yapar.

new_df.drop("Extra", axis = 1, inplace = True)

new_df

          Salary       Age  Seniority
Atil   -0.652160  0.173823   1.060136
Zeynep  0.265248  0.911682  -0.712270
Atlas  -1.265333 -0.507606  -0.798418
Mehmet -0.722587  0.522012   0.735799

In [ ]:
# Sütuna "Mehmet" değişkeni ekleyelim

new_df["Mehmet"] = 10

new_df

          Salary       Age  Seniority  Mehmet
Atil   -0.652160  0.173823   1.060136      10
Zeynep  0.265248  0.911682  -0.712270      10
Atlas  -1.265333 -0.507606  -0.798418      10
Mehmet -0.722587  0.522012   0.735799      10

In [ ]:
# Mehmet isimli veriyi silelim
# axis belirtilmezse default değer 0 olarak satır(row) belirtir.

new_df.drop("Mehmet")

          Salary       Age  Seniority  Mehmet
Atil   -0.652160  0.173823   1.060136      10
Zeynep  0.265248  0.911682  -0.712270      10
Atlas  -1.265333 -0.507606  -0.798418      10

In [ ]:
# Atama olmadığı ve inplace= True yapılmadığı için değişiklik kalıcı olmadı

new_df

          Salary       Age  Seniority  Mehmet
Atil   -0.652160  0.173823   1.060136      10
Zeynep  0.265248  0.911682  -0.712270      10
Atlas  -1.265333 -0.507606  -0.798418      10
Mehmet -0.722587  0.522012   0.735799      10

In [ ]:
# Mehmet isimli sütunu silelim

new_df.drop("Mehmet", axis = 1, inplace = True)

new_df

          Salary       Age  Seniority
Atil   -0.652160  0.173823   1.060136
Zeynep  0.265248  0.911682  -0.712270
Atlas  -1.265333 -0.507606  -0.798418
Mehmet -0.722587  0.522012   0.735799

In [ ]:
# Atlas satırının değerlerini alalım

new_df.loc["Atlas"]

Salary      -1.265333
Age         -0.507606
Seniority   -0.798418
Name: Atlas, dtype: float64

In [ ]:
# Atlas satırının Salary değerini alalım

# new_df.loc["Atlas"]["Salary"] veya

new_df.loc["Atlas", "Salary"]

np.float64(-1.2653333643769318)

In [ ]:
# Atlas'ın Salary değerini değiştirelim

new_df.loc["Atlas", "Salary"] = 100

new_df

            Salary       Age  Seniority
Atil     -0.652160  0.173823   1.060136
Zeynep    0.265248  0.911682  -0.712270
Atlas   100.000000 -0.507606  -0.798418
Mehmet   -0.722587  0.522012   0.735799

In [ ]:
# Filtreme işlemleri yapalım

boolen_frame = new_df > 0

new_df[boolen_frame]

            Salary       Age  Seniority
Atil           NaN  0.173823   1.060136
Zeynep    0.265248  0.911682        NaN
Atlas   100.000000       NaN        NaN
Mehmet         NaN  0.522012   0.735799

In [ ]:
# Aynı filtreleme eşitleme olmadanda doğrudan yapılabilir

new_df[new_df > 0]

            Salary       Age  Seniority
Atil           NaN  0.173823   1.060136
Zeynep    0.265248  0.911682        NaN
Atlas   100.000000       NaN        NaN
Mehmet         NaN  0.522012   0.735799

In [ ]:
# Salary için filtreleme yapalım

new_df[new_df["Salary"] > 1 ]

       Salary       Age  Seniority
Atlas   100.0 -0.507606  -0.798418

In [ ]:
# Age için filtreleme yapalım

new_df[new_df["Age"] > 0 ]

          Salary       Age  Seniority
Atil   -0.652160  0.173823   1.060136
Zeynep  0.265248  0.911682  -0.712270
Mehmet -0.722587  0.522012   0.735799

## ➡  DataFrame Index Mantığı

In [ ]:
# Index atayalım

reset_frame = new_df.reset_index()

reset_frame

    index      Salary       Age  Seniority
0    Atil   -0.652160  0.173823   1.060136
1  Zeynep    0.265248  0.911682  -0.712270
2   Atlas  100.000000 -0.507606  -0.798418
3  Mehmet   -0.722587  0.522012   0.735799

In [ ]:
# loc ile indexe erişme

reset_frame.loc[0]

index            Atil
Salary       -0.65216
Age          0.173823
Seniority    1.060136
Name: 0, dtype: object

In [ ]:
# Yeni index ekleyelim

new_indices = ["Ati", "Zey", "Atl", "Meh"]

new_df["NewIndex"] = new_indices

new_df

            Salary       Age  Seniority NewIndex
Atil     -0.652160  0.173823   1.060136      Ati
Zeynep    0.265248  0.911682  -0.712270      Zey
Atlas   100.000000 -0.507606  -0.798418      Atl
Mehmet   -0.722587  0.522012   0.735799      Meh

In [ ]:
# Fonksiyon ile index oluşturalım

new_df.set_index("NewIndex", inplace = True)

new_df

              Salary       Age  Seniority
NewIndex
Ati        -0.652160  0.173823   1.060136
Zey         0.265248  0.911682  -0.712270
Atl       100.000000 -0.507606  -0.798418
Meh        -0.722587  0.522012   0.735799

In [ ]:
# Yeni indexe göre değeri bulalım

new_df.loc["Ati"]

Salary      -0.652160
Age          0.173823
Seniority    1.060136
Name: Ati, dtype: float64

In [ ]:
# multi index

#İlk indexi oluşturalım

first_index = ["Simpson", "Simpson", "Simpson", "South Park", "South Park", "South Park"]

In [ ]:
# İkinci indexi oluşturalım

inner_index = ["Homer", "Bart", "Marge", "Cartman", "Kenny", "Kyle"]

In [ ]:
# İki indexi birleştirelim

zipped_index = list(zip(first_index, inner_index))

zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [ ]:
# MultiIndex yapısını oluşturalım

zipped_index = pd.MultiIndex.from_tuples(zipped_index)

zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [ ]:
# Örnek data oluşturalım

sample_values = np.ones((6,2))

In [ ]:
# Dataframe oluşturalım

big_df = pd.DataFrame(sample_values, index = zipped_index, columns = ["Age", "Salary"])

big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [ ]:
# Age değerlerine ulaşalım

big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [ ]:
# Homer bilgilerine ulaşalım

big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64

## ➡  DataFrame Excel, csv vs. Okuma

In [ ]:
# Kütüphaneleri yükleyelim

import numpy as np
import pandas as pd

In [ ]:
# Veri setlerini yükleyelim

from google.colab import files
uploaded = files.upload()

Saving 6-weather.xlsx to 6-weather.xlsx

In [ ]:
# Dosyayı okuyalım

weather_df = pd.read_excel("6-weather.xlsx")

weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [ ]:
# İlk 5 veriye bakalım

weather_df.head()

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [ ]:
# Son 5 veriye bakalım

weather_df.tail()

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [ ]:
# Verilerin bilgisine bakalım

weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [ ]:
# Özet istatistiklerine bakalım

weather_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [ ]:
# Kaç data var ve tipi nedir?

weather_df.count()

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [ ]:
# Boş(missing data) var mı?

weather_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False